package com.novel2script.application.service;

import com.novel2script.common.enums.CharacterRoleType;
import com.novel2script.common.enums.Emotion;
import com.novel2script.common.enums.ScriptStatus;
import com.novel2script.common.enums.WorkflowStep;
import com.novel2script.common.exception.BusinessException;
import com.novel2script.domain.model.Action;
import com.novel2script.domain.model.Dialogue;
import com.novel2script.domain.model.PlotEvent;
import com.novel2script.domain.model.Scene;
import com.novel2script.domain.model.Script;
import com.novel2script.domain.model.Character;

import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Application service for script generation and management.
 * Uses in-memory storage as a development fallback.
 *
 * <p>Generation is orchestrated by {@link GenerationOrchestrator},
 * which runs asynchronously and updates the script via the
 * {@code update*} methods on this service.
 */
@Slf4j
@Service
public class ScriptService {

    private final Map<Long, Script> store = new ConcurrentHashMap<>();
    private final AtomicLong idGenerator = new AtomicLong(1);
    private final AtomicLong contentIdSeq = new AtomicLong(System.currentTimeMillis());

    private final GenerationOrchestrator orchestrator;

    public ScriptService(@Lazy GenerationOrchestrator orchestrator) {
        this.orchestrator = orchestrator;
    }

    /**
     * Ensure every dialogue and action across all scenes has a valid non-null ID.
     * Dialogues/actions generated by AI agents may lack IDs; this fills them in.
     */
    private void normalizeContentIds(Script script) {
        if (script == null || script.getScenes() == null) return;
        for (Scene scene : script.getScenes()) {
            if (scene.getDialogues() != null) {
                for (Dialogue d : scene.getDialogues()) {
                    if (d.getId() == null || d.getId() <= 0) {
                        d.setId(contentIdSeq.getAndIncrement());
                    }
                }
            }
            if (scene.getActions() != null) {
                for (Action a : scene.getActions()) {
                    if (a.getId() == null || a.getId() <= 0) {
                        a.setId(contentIdSeq.getAndIncrement());
                    }
                }
            }
        }
    }

    // ─────────────────────────────────────────────────────
    //  Public API — called by controllers
    // ─────────────────────────────────────────────────────

    /** Start script generation (async). Returns immediately with the script stub. */
    public Script generateScript(Long novelId, int maxScenes, String style,
                                  List<String> focusCharacters) {
        log.info("Starting script generation: novelId={}, maxScenes={}, style='{}'",
                novelId, maxScenes, style);

        if (maxScenes < 1 || maxScenes > 100) {
            throw new BusinessException("INVALID_SCENE_COUNT",
                    "maxScenes must be between 1 and 100, got: " + maxScenes);
        }

        Long id = idGenerator.getAndIncrement();
        LocalDateTime now = LocalDateTime.now();

        Map<String, Object> workflowState = new LinkedHashMap<>();
        workflowState.put("maxScenes", maxScenes);
        workflowState.put("style", style != null ? style : "标准");
        workflowState.put("focusCharacters", focusCharacters != null ? focusCharacters : List.of());
        workflowState.put("currentStep", WorkflowStep.CHAPTER_PARSE.name());
        workflowState.put("startedAt", now.toString());

        Script script = Script.builder()
                .id(id)
                .novelId(novelId)
                .title("Generating...")
                .version(1)
                .sceneCount(0)
                .characterCount(0)
                .dialogueCount(0)
                .scenes(new ArrayList<>())
                .characters(new ArrayList<>())
                .plotEvents(new ArrayList<>())
                .workflowState(workflowState)
                .status(ScriptStatus.GENERATING)
                .progress(0.0)
                .createdAt(now)
                .updatedAt(now)
                .build();

        store.put(id, script);

        // Launch async pipeline
        orchestrator.launchGeneration(script);

        log.info("Script generation launched: scriptId={}, novelId={}", id, novelId);
        return script;
    }

    public Optional<Script> findById(Long scriptId) {
        Script script = store.get(scriptId);
        if (script != null) {
            normalizeContentIds(script);
            log.debug("Found script: id={}, status={}", scriptId, script.getStatus());
            return Optional.of(script);
        }
        log.debug("Script not found: id={}", scriptId);
        return Optional.empty();
    }

    /** Save (upsert) a script to the in-memory store. */
    public void save(Script script) {
        if (script.getId() == null) {
            script.setId(idGenerator.getAndIncrement());
        }
        normalizeContentIds(script);
        store.put(script.getId(), script);
    }

    /**
     * Same as {@link #findById} but produces no log output.
     * Used by SSE polling loop to avoid flooding the log every 2 seconds.
     */
    public Optional<Script> findByIdQuietly(Long scriptId) {
        Script script = store.get(scriptId);
        if (script != null) {
            normalizeContentIds(script);
        }
        return Optional.ofNullable(script);
    }

    /** Return stored progress — the orchestrator writes it. */
    public double getProgress(Long scriptId) {
        Script script = store.get(scriptId);
        return script != null ? script.getProgress() : 0.0;
    }

    public String getYaml(Long scriptId) {
        Script script = store.get(scriptId);
        if (script == null) return null;
        if (script.getYamlContent() == null || script.getYamlContent().isBlank()) {
            script.setYamlContent(generateYaml(script));
        }
        return script.getYamlContent();
    }

    /** Generate a human-readable TXT screenplay from the script. */
    public String getTxt(Long scriptId) {
        Script script = store.get(scriptId);
        if (script == null) return null;
        return generateTxt(script);
    }

    /** Generate a Markdown-formatted screenplay from the script. */
    public String getMd(Long scriptId) {
        Script script = store.get(scriptId);
        if (script == null) return null;
        return generateMd(script);
    }

    public List<Script> listAll() {
        return new ArrayList<>(store.values());
    }

    // ─────────────────────────────────────────────────────
    //  Data writers — called by GenerationOrchestrator
    // ─────────────────────────────────────────────────────

    public void updateProgress(Long scriptId, double progress, WorkflowStep step) {
        Script script = store.get(scriptId);
        if (script == null) return;
        script.setProgress(Math.min(100.0, Math.max(0.0, progress)));
        script.getWorkflowState().put("currentStep", step.name());
        script.setUpdatedAt(LocalDateTime.now());
    }

    public void updateCharacters(Long scriptId, List<Character> characters) {
        Script script = store.get(scriptId);
        if (script == null) return;
        script.setCharacters(new ArrayList<>(characters));
        script.setCharacterCount(characters.size());
        script.setUpdatedAt(LocalDateTime.now());
    }

    public void updateScenes(Long scriptId, List<Scene> scenes) {
        Script script = store.get(scriptId);
        if (script == null) return;
        script.setScenes(new ArrayList<>(scenes));
        script.setSceneCount(scenes.size());
        int dialogueCount = scenes.stream().mapToInt(s -> s.getDialogues().size()).sum();
        script.setDialogueCount(dialogueCount);
        normalizeContentIds(script);
        script.setUpdatedAt(LocalDateTime.now());
    }

    public void updatePlotEvents(Long scriptId, List<PlotEvent> plotEvents) {
        Script script = store.get(scriptId);
        if (script == null) return;
        script.setPlotEvents(new ArrayList<>(plotEvents));
        script.setUpdatedAt(LocalDateTime.now());
    }

    public void setTitle(Long scriptId, String title) {
        Script script = store.get(scriptId);
        if (script != null) {
            script.setTitle(title);
            script.setUpdatedAt(LocalDateTime.now());
        }
    }

    public void completeScript(Long scriptId) {
        Script script = store.get(scriptId);
        if (script == null) return;
        script.setProgress(100.0);
        script.setStatus(ScriptStatus.COMPLETED);
        normalizeContentIds(script);
        // Generate final YAML
        script.setYamlContent(generateYaml(script));
        script.setUpdatedAt(LocalDateTime.now());
        log.info("Script completed: id={}, title='{}', scenes={}, characters={}",
                scriptId, script.getTitle(), script.getSceneCount(), script.getCharacterCount());
    }

    public void markFailed(Long scriptId) {
        Script script = store.get(scriptId);
        if (script == null) return;
        script.setStatus(ScriptStatus.FAILED);
        script.setUpdatedAt(LocalDateTime.now());
        log.warn("Script marked FAILED: id={}", scriptId);
    }

    /**
     * Delete a script from the in-memory store.
     * Called by the DELETE /api/v1/scripts/{id} endpoint.
     */
    public void deleteScript(Long scriptId) {
        Script removed = store.remove(scriptId);
        if (removed != null) {
            log.info("Script deleted: id={}, title='{}'", scriptId, removed.getTitle());
        } else {
            log.warn("Script delete requested for non-existent id={}", scriptId);
        }
    }

    // ─────────────────────────────────────────────────────
    //  Paragraph CRUD — actions & dialogues
    // ─────────────────────────────────────────────────────

    private Scene getSceneOrThrow(Script script, Long sceneId) {
        if (script.getScenes() == null) {
            throw new IllegalArgumentException("场景列表为空");
        }
        return script.getScenes().stream()
                .filter(s -> s.getId().equals(sceneId))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("场景不存在: sceneId=" + sceneId));
    }

    public void addAction(Long scriptId, Long sceneId, Action action) {
        Script script = store.get(scriptId);
        if (script == null) throw new IllegalArgumentException("剧本不存在: id=" + scriptId);
        Scene scene = getSceneOrThrow(script, sceneId);
        if (scene.getActions() == null) scene.setActions(new ArrayList<>());
        scene.getActions().add(action);
        script.setUpdatedAt(LocalDateTime.now());
        log.info("Action added: scriptId={}, sceneId={}, actionId={}", scriptId, sceneId, action.getId());
    }

    @SuppressWarnings("unchecked")
    public void updateAction(Long scriptId, Long sceneId, Long actionId, Map<String, Object> updates) {
        Script script = store.get(scriptId);
        if (script == null) throw new IllegalArgumentException("剧本不存在: id=" + scriptId);
        Scene scene = getSceneOrThrow(script, sceneId);

        Action action = scene.getActions().stream()
                .filter(a -> a.getId().equals(actionId))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("动作不存在: actionId=" + actionId));

        if (updates.containsKey("description")) action.setDescription((String) updates.get("description"));
        if (updates.containsKey("actionType")) action.setActionType((String) updates.get("actionType"));
        if (updates.containsKey("sequence")) action.setSequence(((Number) updates.get("sequence")).intValue());
        if (updates.containsKey("characterId")) action.setCharacterId(((Number) updates.get("characterId")).longValue());
        if (updates.containsKey("durationMs")) action.setDurationMs(((Number) updates.get("durationMs")).intValue());

        script.setUpdatedAt(LocalDateTime.now());
        log.info("Action updated: scriptId={}, sceneId={}, actionId={}", scriptId, sceneId, actionId);
    }

    public void deleteAction(Long scriptId, Long sceneId, Long actionId) {
        Script script = store.get(scriptId);
        if (script == null) throw new IllegalArgumentException("剧本不存在: id=" + scriptId);
        Scene scene = getSceneOrThrow(script, sceneId);

        boolean removed = scene.getActions().removeIf(a -> a.getId().equals(actionId));
        if (!removed) throw new IllegalArgumentException("动作不存在: actionId=" + actionId);

        script.setUpdatedAt(LocalDateTime.now());
        log.info("Action deleted: scriptId={}, sceneId={}, actionId={}", scriptId, sceneId, actionId);
    }

    public void addDialogue(Long scriptId, Long sceneId, Dialogue dialogue) {
        Script script = store.get(scriptId);
        if (script == null) throw new IllegalArgumentException("剧本不存在: id=" + scriptId);
        Scene scene = getSceneOrThrow(script, sceneId);
        if (scene.getDialogues() == null) scene.setDialogues(new ArrayList<>());
        scene.getDialogues().add(dialogue);
        script.setUpdatedAt(LocalDateTime.now());
        // Update dialogue count
        script.setDialogueCount(script.getScenes().stream()
                .mapToInt(s -> s.getDialogues() != null ? s.getDialogues().size() : 0).sum());
        log.info("Dialogue added: scriptId={}, sceneId={}, dialogueId={}", scriptId, sceneId, dialogue.getId());
    }

    @SuppressWarnings("unchecked")
    public void updateDialogue(Long scriptId, Long sceneId, Long dialogueId, Map<String, Object> updates) {
        Script script = store.get(scriptId);
        if (script == null) throw new IllegalArgumentException("剧本不存在: id=" + scriptId);
        Scene scene = getSceneOrThrow(script, sceneId);

        Dialogue dialogue = scene.getDialogues().stream()
                .filter(d -> d.getId().equals(dialogueId))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("对白不存在: dialogueId=" + dialogueId));

        if (updates.containsKey("speaker")) dialogue.setSpeaker((String) updates.get("speaker"));
        if (updates.containsKey("content")) dialogue.setContent((String) updates.get("content"));
        if (updates.containsKey("emotion")) {
            String emotionStr = (String) updates.get("emotion");
            dialogue.setEmotion(Emotion.fromLabel(emotionStr));
        }
        if (updates.containsKey("sequence")) dialogue.setSequence(((Number) updates.get("sequence")).intValue());
        if (updates.containsKey("characterId")) dialogue.setCharacterId(((Number) updates.get("characterId")).longValue());
        if (updates.containsKey("parenthetical")) dialogue.setParenthetical((String) updates.get("parenthetical"));

        script.setUpdatedAt(LocalDateTime.now());
        log.info("Dialogue updated: scriptId={}, sceneId={}, dialogueId={}", scriptId, sceneId, dialogueId);
    }

    public void deleteDialogue(Long scriptId, Long sceneId, Long dialogueId) {
        Script script = store.get(scriptId);
        if (script == null) throw new IllegalArgumentException("剧本不存在: id=" + scriptId);
        Scene scene = getSceneOrThrow(script, sceneId);

        boolean removed = scene.getDialogues().removeIf(d -> d.getId().equals(dialogueId));
        if (!removed) throw new IllegalArgumentException("对白不存在: dialogueId=" + dialogueId);

        script.setUpdatedAt(LocalDateTime.now());
        // Update dialogue count
        script.setDialogueCount(script.getScenes().stream()
                .mapToInt(s -> s.getDialogues() != null ? s.getDialogues().size() : 0).sum());
        log.info("Dialogue deleted: scriptId={}, sceneId={}, dialogueId={}", scriptId, sceneId, dialogueId);
    }

    @SuppressWarnings("unchecked")
    public void reorderSceneContent(Long scriptId, Long sceneId, List<Map<String, Object>> items) {
        Script script = store.get(scriptId);
        if (script == null) throw new IllegalArgumentException("剧本不存在: id=" + scriptId);
        Scene scene = getSceneOrThrow(script, sceneId);

        // items: [{type: "action"|"dialogue", id: number, sequence: number}, ...]
        for (Map<String, Object> item : items) {
            String type = (String) item.get("type");
            Long itemId = ((Number) item.get("id")).longValue();
            int sequence = ((Number) item.get("sequence")).intValue();

            if ("action".equals(type)) {
                scene.getActions().stream()
                        .filter(a -> a.getId().equals(itemId))
                        .findFirst()
                        .ifPresent(a -> a.setSequence(sequence));
            } else if ("dialogue".equals(type)) {
                scene.getDialogues().stream()
                        .filter(d -> d.getId().equals(itemId))
                        .findFirst()
                        .ifPresent(d -> d.setSequence(sequence));
            }
        }
        script.setUpdatedAt(LocalDateTime.now());
        log.info("Scene content reordered: scriptId={}, sceneId={}, items={}", scriptId, sceneId, items.size());
    }

    @SuppressWarnings("unchecked")
    public void updateCharacter(Long scriptId, Long characterId, Map<String, Object> updates) {
        Script script = store.get(scriptId);
        if (script == null) throw new IllegalArgumentException("剧本不存在: id=" + scriptId);

        Character character = script.getCharacters().stream()
                .filter(c -> c.getId().equals(characterId))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("角色不存在: characterId=" + characterId));

        // Snapshot old canonical name before mutation (for speaker propagation)
        String oldName = character.getCanonicalName();

        if (updates.containsKey("canonicalName"))
            character.setCanonicalName((String) updates.get("canonicalName"));
        if (updates.containsKey("roleType")) {
            String roleStr = (String) updates.get("roleType");
            character.setRoleType(CharacterRoleType.fromValue(roleStr));
        }
        if (updates.containsKey("gender"))
            character.setGender((String) updates.get("gender"));
        if (updates.containsKey("ageRange"))
            character.setAgeRange((String) updates.get("ageRange"));
        if (updates.containsKey("description"))
            character.setDescription((String) updates.get("description"));
        if (updates.containsKey("aliases")) {
            Object aliasesObj = updates.get("aliases");
            if (aliasesObj instanceof List) {
                character.setAliases((List<String>) aliasesObj);
            }
        }
        if (updates.containsKey("personality")) {
            Object personalityObj = updates.get("personality");
            if (personalityObj instanceof List) {
                character.setPersonality((List<String>) personalityObj);
            }
        }
        if (updates.containsKey("relationships")) {
            Object relsObj = updates.get("relationships");
            if (relsObj instanceof List) {
                List<Map<String, String>> rawRels = (List<Map<String, String>>) relsObj;
                List<Character.Relationship> relationships = new ArrayList<>();
                for (Map<String, String> r : rawRels) {
                    relationships.add(Character.Relationship.builder()
                            .target(r.get("target"))
                            .relation(r.get("relation"))
                            .build());
                }
                character.setRelationships(relationships);
            }
        }

        // Propagate canonical name change to dialogue speaker fields
        String newName = character.getCanonicalName();
        if (oldName != null && !oldName.equals(newName)) {
            int updatedCount = 0;
            for (Scene scene : script.getScenes()) {
                for (Dialogue dialogue : scene.getDialogues()) {
                    // Match by characterId (precise) or by speaker name (fallback)
                    if (dialogue.getCharacterId() != null
                            && dialogue.getCharacterId().equals(characterId)) {
                        dialogue.setSpeaker(newName);
                        updatedCount++;
                    } else if (oldName.equals(dialogue.getSpeaker())) {
                        dialogue.setSpeaker(newName);
                        updatedCount++;
                    }
                }
            }
            log.info("Character name changed: '{}' -> '{}', synced {} dialogue(s)",
                    oldName, newName, updatedCount);
        }

        // Invalidate YAML cache so it regenerates with updated data
        script.setYamlContent(null);

        script.setUpdatedAt(LocalDateTime.now());
        log.info("Character updated: scriptId={}, characterId={}, fields={}",
                scriptId, characterId, updates.keySet());
    }

    public void updateYaml(Long scriptId, String yamlContent) {
        Script script = store.get(scriptId);
        if (script != null) {
            script.setYamlContent(yamlContent);
            script.setUpdatedAt(LocalDateTime.now());
        }
    }

    // ─────────────────────────────────────────────────────
    //  YAML generation
    // ─────────────────────────────────────────────────────

    private String generateYaml(Script script) {
        StringBuilder sb = new StringBuilder();
        sb.append("script:\n");
        sb.append("  id: ").append(script.getId()).append("\n");
        sb.append("  novelId: ").append(script.getNovelId()).append("\n");
        sb.append("  title: \"").append(esc(script.getTitle())).append("\"\n");
        sb.append("  status: \"").append(script.getStatus()).append("\"\n");
        sb.append("  version: ").append(script.getVersion()).append("\n");

        // Count actual data lengths (not stored fields which may be stale)
        int sceneCount = script.getScenes() != null ? script.getScenes().size() : 0;
        int characterCount = script.getCharacters() != null ? script.getCharacters().size() : 0;
        int dialogueCount = script.getScenes() != null
                ? script.getScenes().stream().mapToInt(s -> s.getDialogues() != null ? s.getDialogues().size() : 0).sum()
                : 0;

        sb.append("  sceneCount: ").append(sceneCount).append("\n");
        sb.append("  characterCount: ").append(characterCount).append("\n");
        sb.append("  dialogueCount: ").append(dialogueCount).append("\n");

        // --- characters ---
        sb.append("\n  characters:\n");
        if (script.getCharacters() != null) {
            for (Character c : script.getCharacters()) {
                sb.append("    - id: ").append(validateId(c.getId(), 1000)).append("\n");
                sb.append("      canonicalName: \"").append(esc(c.getCanonicalName())).append("\"\n");
                sb.append("      roleType: \"").append(c.getRoleType() != null ? c.getRoleType().name() : "SUPPORTING").append("\"\n");
                sb.append("      gender: \"").append(c.getGender() != null ? c.getGender() : "OTHER").append("\"\n");
                if (c.getDescription() != null && !c.getDescription().isBlank())
                    sb.append("      description: \"").append(esc(c.getDescription())).append("\"\n");
                if (c.getPersonality() != null && !c.getPersonality().isEmpty()) {
                    sb.append("      personality:");
                    for (String p : c.getPersonality()) {
                        sb.append("\n        - \"").append(esc(p)).append("\"");
                    }
                    sb.append("\n");
                }
                if (c.getRelationships() != null && !c.getRelationships().isEmpty()) {
                    sb.append("      relationships:\n");
                    for (Character.Relationship r : c.getRelationships()) {
                        sb.append("        - target: \"").append(esc(r.getTarget()))
                          .append("\"\n          relation: \"").append(esc(r.getRelation()))
                          .append("\"\n");
                    }
                }
            }
        }

        // --- scenes ---
        sb.append("\n  scenes:\n");
        if (script.getScenes() != null) {
            for (Scene s : script.getScenes()) {
                sb.append("    - id: ").append(validateId(s.getId(), 1100)).append("\n");
                sb.append("      sceneNumber: ").append(s.getSceneNumber()).append("\n");
                sb.append("      location: \"").append(esc(s.getLocation())).append("\"\n");
                sb.append("      timeOfDay: \"").append(s.getTimeOfDay() != null ? s.getTimeOfDay().name() : "UNSPECIFIED").append("\"\n");
                sb.append("      interior: ").append(s.isInterior()).append("\n");
                sb.append("      title: \"").append(esc(s.getTitle() != null ? s.getTitle() : "")).append("\"\n");
                sb.append("      mood: \"").append(esc(s.getMood() != null ? s.getMood() : "")).append("\"\n");
                sb.append("      sceneHeading: \"").append(esc(s.getSceneHeader())).append("\"\n");

                // dialogues
                if (s.getDialogues() != null && !s.getDialogues().isEmpty()) {
                    sb.append("      dialogues:\n");
                    for (Dialogue d : s.getDialogues()) {
                        sb.append("        - id: ").append(validateId(d.getId(), 1)).append("\n");
                        sb.append("          speaker: \"").append(esc(d.getSpeaker())).append("\"\n");
                        sb.append("          content: \"").append(esc(d.getContent())).append("\"\n");
                        sb.append("          emotion: \"").append(d.getEmotion() != null ? d.getEmotion().name() : "CALM").append("\"\n");
                        if (d.getParenthetical() != null && !d.getParenthetical().isBlank())
                            sb.append("          parenthetical: \"").append(esc(d.getParenthetical())).append("\"\n");
                    }
                }

                // actions
                if (s.getActions() != null && !s.getActions().isEmpty()) {
                    sb.append("      actions:\n");
                    for (Action a : s.getActions()) {
                        sb.append("        - id: ").append(validateId(a.getId(), 1)).append("\n");
                        sb.append("          actionType: \"").append(esc(a.getActionType())).append("\"\n");
                        sb.append("          description: \"").append(esc(a.getDescription())).append("\"\n");
                    }
                }
            }
        }

        return sb.toString();
    }

    /** Ensure ID is non-null and reasonable for display. */
    private static long validateId(Long id, long fallback) {
        return id != null && id > 0 ? id : fallback;
    }

    private String generateTxt(Script script) {
        StringBuilder sb = new StringBuilder();

        // Title
        sb.append("《").append(script.getTitle() != null ? script.getTitle() : "未命名剧本").append("》\n\n");

        List<Scene> scenes = script.getScenes();
        if (scenes == null || scenes.isEmpty()) {
            sb.append("（暂无场景内容）\n");
            return sb.toString();
        }

        // Build character name → Character map for lookups
        Map<Long, Character> charMap = new LinkedHashMap<>();
        if (script.getCharacters() != null) {
            for (Character c : script.getCharacters()) {
                charMap.put(c.getId(), c);
            }
        }

        for (int i = 0; i < scenes.size(); i++) {
            Scene scene = scenes.get(i);

            // Scene header
            sb.append("═══════════════════════════════════════\n");
            sb.append("场景 ").append(scene.getSceneNumber());
            String heading = scene.getSceneHeader();
            if (heading != null && !heading.isBlank()) {
                sb.append("：").append(heading);
            } else {
                sb.append("：").append(scene.getLocation() != null ? scene.getLocation() : "未知地点");
                if (scene.getTimeOfDay() != null && !"UNKNOWN".equalsIgnoreCase(scene.getTimeOfDay().name())) {
                    sb.append(" - ").append(formatTimeOfDay(scene.getTimeOfDay().name()));
                }
            }
            sb.append("\n");
            sb.append("═══════════════════════════════════════\n\n");

            // Characters in scene
            if (scene.getCharacterIds() != null && !scene.getCharacterIds().isEmpty()) {
                sb.append("出场角色：");
                List<String> names = new ArrayList<>();
                for (Long cid : scene.getCharacterIds()) {
                    Character c = charMap.get(cid);
                    if (c != null) names.add(c.getCanonicalName());
                }
                sb.append(String.join("、", names));
                sb.append("\n\n");
            }

            // Mood
            if (scene.getMood() != null && !scene.getMood().isBlank()) {
                sb.append("场景氛围：").append(scene.getMood()).append("\n\n");
            }

            // Summary
            if (scene.getSummary() != null && !scene.getSummary().isBlank()) {
                sb.append("摘要：").append(scene.getSummary()).append("\n\n");
            }

            sb.append("───────────────────────────────────────\n\n");

            // Merge dialogues and actions sorted by sequence
            List<Object> contentItems = new ArrayList<>();
            if (scene.getDialogues() != null) contentItems.addAll(scene.getDialogues());
            if (scene.getActions() != null) contentItems.addAll(scene.getActions());
            contentItems.sort((a, b) -> {
                int sa = (a instanceof Dialogue) ? ((Dialogue) a).getSequence() : ((Action) a).getSequence();
                int sb2 = (b instanceof Dialogue) ? ((Dialogue) b).getSequence() : ((Action) b).getSequence();
                return Integer.compare(sa, sb2);
            });

            for (Object item : contentItems) {
                if (item instanceof Dialogue d) {
                    sb.append("  ").append(d.getSpeaker());
                    if (d.getEmotion() != null) {
                        sb.append("（").append(emotionLabel(d.getEmotion().name())).append("）");
                    }
                    if (d.getParenthetical() != null && !d.getParenthetical().isBlank()) {
                        sb.append("（").append(d.getParenthetical()).append("）");
                    }
                    sb.append("：\"").append(d.getContent()).append("\"\n\n");
                } else if (item instanceof Action a) {
                    sb.append("  [").append(actionTypeLabel(a.getActionType())).append("] ");
                    sb.append(a.getDescription());
                    if (a.getDurationMs() != null && a.getDurationMs() > 0) {
                        sb.append(" （约").append(String.format("%.1f", a.getDurationMs() / 1000.0)).append("秒）");
                    }
                    sb.append("\n\n");
                }
            }

            sb.append("───────────────────────────────────────\n\n");
        }

        return sb.toString();
    }

    private String generateMd(Script script) {
        StringBuilder sb = new StringBuilder();

        // Title
        sb.append("# 《").append(script.getTitle() != null ? script.getTitle() : "未命名剧本").append("》\n\n");

        List<Scene> scenes = script.getScenes();
        if (scenes == null || scenes.isEmpty()) {
            sb.append("> （暂无场景内容）\n");
            return sb.toString();
        }

        // Build character map
        Map<Long, Character> charMap = new LinkedHashMap<>();
        if (script.getCharacters() != null) {
            for (Character c : script.getCharacters()) {
                charMap.put(c.getId(), c);
            }
        }

        for (int i = 0; i < scenes.size(); i++) {
            Scene scene = scenes.get(i);

            // Scene heading (H2)
            sb.append("---\n\n");
            sb.append("## 场景 ").append(scene.getSceneNumber());
            String heading = scene.getSceneHeader();
            if (heading != null && !heading.isBlank()) {
                sb.append("：").append(heading);
            } else {
                sb.append("：").append(scene.getLocation() != null ? scene.getLocation() : "未知地点");
                if (scene.getTimeOfDay() != null && !"UNKNOWN".equalsIgnoreCase(scene.getTimeOfDay().name())) {
                    sb.append(" - ").append(formatTimeOfDay(scene.getTimeOfDay().name()));
                }
            }
            sb.append("\n\n");

            // Characters
            if (scene.getCharacterIds() != null && !scene.getCharacterIds().isEmpty()) {
                sb.append("**出场角色**：");
                List<String> names = new ArrayList<>();
                for (Long cid : scene.getCharacterIds()) {
                    Character c = charMap.get(cid);
                    if (c != null) names.add(c.getCanonicalName());
                }
                sb.append(String.join("、", names));
                sb.append("\n\n");
            }

            // Mood
            if (scene.getMood() != null && !scene.getMood().isBlank()) {
                sb.append("**场景氛围**：").append(scene.getMood()).append("\n\n");
            }

            // Summary (blockquote)
            if (scene.getSummary() != null && !scene.getSummary().isBlank()) {
                sb.append("> ").append(scene.getSummary()).append("\n\n");
            }

            // Merge and sort content
            List<Object> contentItems = new ArrayList<>();
            if (scene.getDialogues() != null) contentItems.addAll(scene.getDialogues());
            if (scene.getActions() != null) contentItems.addAll(scene.getActions());
            contentItems.sort((a, b) -> {
                int sa = (a instanceof Dialogue) ? ((Dialogue) a).getSequence() : ((Action) a).getSequence();
                int sb2 = (b instanceof Dialogue) ? ((Dialogue) b).getSequence() : ((Action) b).getSequence();
                return Integer.compare(sa, sb2);
            });

            for (Object item : contentItems) {
                if (item instanceof Dialogue d) {
                    sb.append("**").append(d.getSpeaker()).append("**");
                    if (d.getEmotion() != null) {
                        String el = emotionLabel(d.getEmotion().name());
                        if (!el.isEmpty()) sb.append("（").append(el).append("）");
                    }
                    if (d.getParenthetical() != null && !d.getParenthetical().isBlank()) {
                        sb.append("（").append(d.getParenthetical()).append("）");
                    }
                    sb.append("：\"").append(d.getContent()).append("\"\n\n");
                } else if (item instanceof Action a) {
                    sb.append("*[").append(actionTypeLabel(a.getActionType())).append("]* ");
                    sb.append(a.getDescription());
                    if (a.getDurationMs() != null && a.getDurationMs() > 0) {
                        sb.append(" （约").append(String.format("%.1f", a.getDurationMs() / 1000.0)).append("秒）");
                    }
                    sb.append("\n\n");
                }
            }
        }

        return sb.toString();
    }

    private static String formatTimeOfDay(String tod) {
        if (tod == null) return "";
        return switch (tod) {
            case "MORNING" -> "早晨";
            case "AFTERNOON" -> "下午";
            case "EVENING" -> "傍晚";
            case "NIGHT" -> "夜晚";
            case "DAWN" -> "黎明";
            case "LATE_NIGHT" -> "深夜";
            default -> tod;
        };
    }

    private static String emotionLabel(String emotion) {
        if (emotion == null) return "";
        return switch (emotion) {
            case "ANGRY" -> "愤怒";
            case "HAPPY" -> "开心";
            case "SAD" -> "悲伤";
            case "CALM" -> "平静";
            case "FEARFUL" -> "恐惧";
            case "SURPRISED" -> "惊讶";
            case "NEUTRAL" -> "";
            default -> emotion;
        };
    }

    private static String actionTypeLabel(String type) {
        if (type == null) return "动作";
        return switch (type) {
            case "ACTION" -> "动作";
            case "REACTION" -> "反应";
            case "BEAT" -> "节拍";
            case "BUSINESS" -> "调度";
            default -> type;
        };
    }

    private static String esc(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
